// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gust.Models;

namespace gust.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("gust.Models.Airport", b =>
                {
                    b.Property<int>("airport_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("airport_name");

                    b.Property<string>("ident");

                    b.Property<string>("iso_country");

                    b.Property<string>("iso_region");

                    b.Property<int>("latitude_deg");

                    b.Property<int>("longitude_deg");

                    b.HasKey("airport_id");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("gust.Models.Runway", b =>
                {
                    b.Property<int>("runway_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("airport_ident");

                    b.Property<int>("airport_ref");

                    b.Property<int>("he_heading_degT");

                    b.Property<string>("he_ident");

                    b.Property<int>("le_heading_degT");

                    b.Property<string>("le_ident");

                    b.HasKey("runway_id");

                    b.ToTable("Runways");
                });
#pragma warning restore 612, 618
        }
    }
}
